apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hestekur-dev
commonLabels:
  environment: dev
commonAnnotations:
  note: Marta i farta
resources:
- ../../base
- serviceaccount.yaml
images:
- name: app-image
  newName: eu.gcr.io/entur-system-1287/hest-er-best
  newTag: pr-11
