app: hest-er-best
shortname: hest
team: plattform
ingress:
  trafficType: public
  host: hest-er-best.dev.entur.io
container:
  image: "eu.gcr.io/entur-system-1287/hest-er-best:pr-11"
  cpu: 0.2
  memory: 256
  probes:
    liveness:
      path: "/greet"
    readiness:
      path: "/greet"
  prometheus:
    enabled: false
env: dev
