---
# Source: hest-er-best/charts/common/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hest-er-best-med-helm
  namespace: default
  labels:
    app: hest-er-best-med-helm
    shortname: hest
    team: plattform
    common: 1.17.3
    environment: dev
spec:
  minAvailable: 0%
  selector:
    matchLabels:
      app: hest-er-best-med-helm
---
# Source: hest-er-best/charts/common/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hest-er-best-med-helm
    shortname: hest
    team: plattform
    common: 1.17.3
    environment: dev
  name: hest-er-best-med-helm
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hest-er-best-med-helm
  type: ClusterIP
---
# Source: hest-er-best/charts/common/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hest-er-best-med-helm
    shortname: hest
    team: plattform
    common: 1.17.3
    environment: dev
  name: hest-er-best-med-helm
  namespace: default
spec:
  selector:
    matchLabels:
      app: hest-er-best-med-helm
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: hest-er-best-med-helm
        shortname: hest
        team: plattform
        common: 1.17.3
        environment: dev
    spec:
      serviceAccountName: application

      containers:
      
        - name: hest-er-best
          image: eu.gcr.io/entur-system-1287/hest-er-best:pr-12
          imagePullPolicy: Always
          
          env:
            []
          
          ports:
            - containerPort: 8080
              protocol: TCP
          
          resources:
            limits:
              memory: "307Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          
          livenessProbe:
            httpGet:
              path: /greet
              port: 8080
            initialDelaySeconds: 0
            successThreshold: 1
            failureThreshold: 6
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /greet
              port: 8080
            initialDelaySeconds: 0
            successThreshold: 1
            failureThreshold: 6
            periodSeconds: 5
          startupProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 300
            periodSeconds: 1      
      topologySpreadConstraints:
        - maxSkew: 3
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: hest-er-best-med-helm
        - maxSkew: 5
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: hest-er-best-med-helm
      restartPolicy: Always
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
---
# Source: hest-er-best/charts/common/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    traffic-type: public
    app: hest-er-best-med-helm
    shortname: hest
    team: plattform
    common: 1.17.3
    environment: dev
  name: hest-er-best-med-helm
  namespace: default
spec:
  rules:
  - host: hest-er-best.dev.entur.io
    http:
      paths:
      - backend:
          service:
            name: hest-er-best-med-helm
            port:
              number: 80
        pathType: ImplementationSpecific

# Must manually print newlines for unittest, do not remove
---
# Source: hest-er-best/charts/common/templates/vpa.yaml
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: hest-er-best-med-helm
  namespace: default
  labels:
    app: hest-er-best-med-helm
    shortname: hest
    team: plattform
    common: 1.17.3
    environment: dev
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: hest-er-best-med-helm
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources: ["cpu", "memory"]
  updatePolicy:
    updateMode: "Off"
