apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hestekur-dev
commonLabels:
  environment: dev
commonAnnotations:
  note: Marta i farta
resources:
- ../../base  # default for all environments
- serviceaccount.yaml
- deployment.yaml
patches:
- patch: |- # deleting whole ingress resource, not needed for this test
    $patch: delete
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: hest-er-best-med-helm