apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hestekur-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/entur/tmp-actions-with-argo.git
      revision: main
      directories:
      - path: .argo/hestekur/overlays/*
  template:
    metadata:
      name: '{{path[1]}}-{{path[3]}}'
    spec:
      project: hestekur
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/entur/tmp-actions-with-argo.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}-{{path[3]}}'