apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hestekur-prd
commonLabels:
  environment: prd
commonAnnotations:
  note: Marta i farta
resources:
- ../../base  # default for all environments
- serviceaccount.yaml


