name: Deploy Tst

on:
  pull_request_review:
    types:
      - submitted

jobs:
  tf-apply:
    name: Terraform apply tst
    if: github.event.review.state == 'approved'
    uses: entur/tmp-github-actions-2/.github/workflows/tf-apply.yml@master
    with:
      tf_version: 1.1.0
      environment: tst
    secrets: inherit

  helm-deploy:
    name: Deploy app to tst
    if: github.event.review.state == 'approved'
    uses: entur/tmp-github-actions-2/.github/workflows/helm-deploy.yml@master
    with:
      release_name: hest-er-best
      namespace: hest-er-best
      environment: tst
      image_tag: ${{ github.event.pull_request.id }}-pr
    needs: tf-apply
    secrets: inherit
