name: Push Docker Image

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - edited
jobs:
  push-docker:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: push-docker
        run: echo "Push docker"
  awaiting-approval:
    runs-on: ubuntu-latest
    if: github.event.review.state != 'approved'
    steps:
      - name: needs-approval
        run: exit 1
  # cd-docker:
  #   name: CD Docker
  #   uses: entur/tmp-github-actions-2/.github/workflows/cd-docker.yml@master
  #   if: github.event.review.state == 'approved'
  #   with:
  #     app_name: hest-er-best
  #   secrets: inherit
