name: Push Docker Image

on:
  pull_request_review:
    types:
      - submitted

jobs:
  cd-docker:
    name: CD Docker
    if: github.event.review.state == 'approved'
    uses: entur/tmp-github-actions-2/.github/workflows/cd-docker.yml@master
    with:
      app_name: hest-er-best
    secrets: inherit
