on:
  push:
    branches:
      - "main"
env:
  IMAGE: "eu.gcr.io/entur-system-1287/hest-er-best"
  VERSION: "pr-11"
  ENV: "dev"

jobs:
  update-image-tag:
    name: "Update Image"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Git checkout"
        uses: "actions/checkout@v2"
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      - name: "Update Deployment Image Tag" # [3]
        working-directory: ".kustomize/overlays/${{ env.ENV }}"
        run: |
          ../../../kustomize edit set image app-image=${{ env.IMAGE }}:${{ env.VERSION }}
      - name: "Push Updated Image Tag ${{ env.ENV }}"
        working-directory: ".kustomize/overlays/${{ env.ENV }}"
        run: |
          git add .
          git config --global user.name "@github-actions-bot"
          git config --global user.email "github-actions-bot@users.noreply.github.com"
          git commit -am "feat: Update deployment image tag in ${{ env.VERSION }} to ${{ env.VERSION }} [skip ci]"
          git push