name: Argo flow

on:
  workflow_call:
    inputs:
      watch:
        type: string
        default: src
      environment:
        type: string
        default: prd
      app_name:
        required: true
        type: string
      download_artifact:
        type: boolean
        default: true
    outputs:
      image-id:
        value: ${{ jobs.cd-docker.outputs.image-id || jobs.cd-redeploy.outputs.image-id }}

jobs:
  cd-docker:
    name: CD Docker
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: SetImageId
        uses: ./.github/actions/kustomize

